/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISimpleBean', 'model/AppTokenSimpleBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISimpleBean'), require('./AppTokenSimpleBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.AccessToken = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.APISimpleBean, root.ApiManagerPortal.AppTokenSimpleBean);
  }
}(this, function(ApiClient, APISimpleBean, AppTokenSimpleBean) {
  'use strict';




  /**
   * The AccessToken model module.
   * @module model/AccessToken
   * @version 2.0
   */

  /**
   * Constructs a new <code>AccessToken</code>.
   * Access token model
   * @alias module:model/AccessToken
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>AccessToken</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccessToken} obj Optional instance to populate.
   * @return {module:model/AccessToken} The populated <code>AccessToken</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apis')) {
        obj['apis'] = ApiClient.convertToType(data['apis'], [APISimpleBean]);
      }
      if (data.hasOwnProperty('app')) {
        obj['app'] = AppTokenSimpleBean.constructFromObject(data['app']);
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('creationDate')) {
        obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
      }
      if (data.hasOwnProperty('expiredDate')) {
        obj['expiredDate'] = ApiClient.convertToType(data['expiredDate'], 'Date');
      }
      if (data.hasOwnProperty('expiresIn')) {
        obj['expiresIn'] = ApiClient.convertToType(data['expiresIn'], 'Number');
      }
      if (data.hasOwnProperty('extraInfo')) {
        obj['extraInfo'] = ApiClient.convertToType(data['extraInfo'], Object);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('owner')) {
        obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
      }
      if (data.hasOwnProperty('planIds')) {
        obj['planIds'] = ApiClient.convertToType(data['planIds'], ['Number']);
      }
      if (data.hasOwnProperty('refreshToken')) {
        obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/APISimpleBean>} apis
   */
  exports.prototype['apis'] = undefined;
  /**
   * @member {module:model/AppTokenSimpleBean} app
   */
  exports.prototype['app'] = undefined;
  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {Date} creationDate
   */
  exports.prototype['creationDate'] = undefined;
  /**
   * @member {Date} expiredDate
   */
  exports.prototype['expiredDate'] = undefined;
  /**
   * @member {Number} expiresIn
   */
  exports.prototype['expiresIn'] = undefined;
  /**
   * @member {Object} extraInfo
   */
  exports.prototype['extraInfo'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} owner
   */
  exports.prototype['owner'] = undefined;
  /**
   * @member {Array.<Number>} planIds
   */
  exports.prototype['planIds'] = undefined;
  /**
   * @member {String} refreshToken
   */
  exports.prototype['refreshToken'] = undefined;
  /**
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {module:model/AccessToken.StatusEnum} status
   */
  exports.prototype['status'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",
    /**
     * value: "REVOKED"
     * @const
     */
    "REVOKED": "REVOKED",
    /**
     * value: "EXPIRED"
     * @const
     */
    "EXPIRED": "EXPIRED"  };


  return exports;
}));


