/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.APIUserBean = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.UserBean);
  }
}(this, function(ApiClient, UserBean) {
  'use strict';




  /**
   * The APIUserBean model module.
   * @module model/APIUserBean
   * @version 2.0
   */

  /**
   * Constructs a new <code>APIUserBean</code>.
   * @alias module:model/APIUserBean
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>APIUserBean</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIUserBean} obj Optional instance to populate.
   * @return {module:model/APIUserBean} The populated <code>APIUserBean</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = UserBean.constructFromObject(data['user']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/APIUserBean.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/UserBean} user
   */
  exports.prototype['user'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "VIEW"
     * @const
     */
    "VIEW": "VIEW",
    /**
     * value: "EDIT"
     * @const
     */
    "EDIT": "EDIT"  };


  return exports;
}));


