/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CacheMetricItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CacheMetricItem'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.CacheMetric = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.CacheMetricItem);
  }
}(this, function(ApiClient, CacheMetricItem) {
  'use strict';




  /**
   * The CacheMetric model module.
   * @module model/CacheMetric
   * @version 2.0
   */

  /**
   * Constructs a new <code>CacheMetric</code>.
   * @alias module:model/CacheMetric
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CacheMetric</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CacheMetric} obj Optional instance to populate.
   * @return {module:model/CacheMetric} The populated <code>CacheMetric</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('itens')) {
        obj['itens'] = ApiClient.convertToType(data['itens'], [CacheMetricItem]);
      }
      if (data.hasOwnProperty('limit')) {
        obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CacheMetricItem>} itens
   */
  exports.prototype['itens'] = undefined;
  /**
   * @member {Number} limit
   */
  exports.prototype['limit'] = undefined;



  return exports;
}));


