/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangeLogBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangeLogBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.ChangeLogBean = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.ChangeLogBean);
  }
}(this, function(ApiClient, ChangeLogBean) {
  'use strict';




  /**
   * The ChangeLogBean model module.
   * @module model/ChangeLogBean
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChangeLogBean</code>.
   * @alias module:model/ChangeLogBean
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>ChangeLogBean</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangeLogBean} obj Optional instance to populate.
   * @return {module:model/ChangeLogBean} The populated <code>ChangeLogBean</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('action')) {
        obj['action'] = ApiClient.convertToType(data['action'], 'String');
      }
      if (data.hasOwnProperty('creationDate')) {
        obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
      }
      if (data.hasOwnProperty('credentialId')) {
        obj['credentialId'] = ApiClient.convertToType(data['credentialId'], 'Number');
      }
      if (data.hasOwnProperty('credentialLogin')) {
        obj['credentialLogin'] = ApiClient.convertToType(data['credentialLogin'], 'String');
      }
      if (data.hasOwnProperty('credentialName')) {
        obj['credentialName'] = ApiClient.convertToType(data['credentialName'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('jsonAfter')) {
        obj['jsonAfter'] = ApiClient.convertToType(data['jsonAfter'], 'String');
      }
      if (data.hasOwnProperty('jsonBefore')) {
        obj['jsonBefore'] = ApiClient.convertToType(data['jsonBefore'], 'String');
      }
      if (data.hasOwnProperty('objectId')) {
        obj['objectId'] = ApiClient.convertToType(data['objectId'], 'Number');
      }
      if (data.hasOwnProperty('objectType')) {
        obj['objectType'] = ApiClient.convertToType(data['objectType'], 'String');
      }
      if (data.hasOwnProperty('parent')) {
        obj['parent'] = ChangeLogBean.constructFromObject(data['parent']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ChangeLogBean.ActionEnum} action
   */
  exports.prototype['action'] = undefined;
  /**
   * @member {Date} creationDate
   */
  exports.prototype['creationDate'] = undefined;
  /**
   * @member {Number} credentialId
   */
  exports.prototype['credentialId'] = undefined;
  /**
   * @member {String} credentialLogin
   */
  exports.prototype['credentialLogin'] = undefined;
  /**
   * @member {String} credentialName
   */
  exports.prototype['credentialName'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} jsonAfter
   */
  exports.prototype['jsonAfter'] = undefined;
  /**
   * @member {String} jsonBefore
   */
  exports.prototype['jsonBefore'] = undefined;
  /**
   * @member {Number} objectId
   */
  exports.prototype['objectId'] = undefined;
  /**
   * @member {module:model/ChangeLogBean.ObjectTypeEnum} objectType
   */
  exports.prototype['objectType'] = undefined;
  /**
   * @member {module:model/ChangeLogBean} parent
   */
  exports.prototype['parent'] = undefined;


  /**
   * Allowed values for the <code>action</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ActionEnum = {
    /**
     * value: "CREATED"
     * @const
     */
    "CREATED": "CREATED",
    /**
     * value: "UPDATED"
     * @const
     */
    "UPDATED": "UPDATED",
    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED"  };

  /**
   * Allowed values for the <code>objectType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ObjectTypeEnum = {
    /**
     * value: "APP_TOKEN"
     * @const
     */
    "APP_TOKEN": "APP_TOKEN",
    /**
     * value: "AUTH_TOKEN"
     * @const
     */
    "AUTH_TOKEN": "AUTH_TOKEN",
    /**
     * value: "API_DEFINITION"
     * @const
     */
    "API_DEFINITION": "API_DEFINITION",
    /**
     * value: "USER_ACCOUNT"
     * @const
     */
    "USER_ACCOUNT": "USER_ACCOUNT",
    /**
     * value: "ACCESS_CREDENTIAL"
     * @const
     */
    "ACCESS_CREDENTIAL": "ACCESS_CREDENTIAL",
    /**
     * value: "EXTERNAL_LISTENER"
     * @const
     */
    "EXTERNAL_LISTENER": "EXTERNAL_LISTENER",
    /**
     * value: "APICOMPONENTINTERCEPTOR"
     * @const
     */
    "APICOMPONENTINTERCEPTOR": "APICOMPONENTINTERCEPTOR",
    /**
     * value: "PLANINTERCEPTOR"
     * @const
     */
    "PLANINTERCEPTOR": "PLANINTERCEPTOR",
    /**
     * value: "PLAN"
     * @const
     */
    "PLAN": "PLAN",
    /**
     * value: "CUSTOM_INTERCEPTOR"
     * @const
     */
    "CUSTOM_INTERCEPTOR": "CUSTOM_INTERCEPTOR",
    /**
     * value: "CUSTOM_JAVA_INTERCEPTOR"
     * @const
     */
    "CUSTOM_JAVA_INTERCEPTOR": "CUSTOM_JAVA_INTERCEPTOR",
    /**
     * value: "BAAS"
     * @const
     */
    "BAAS": "BAAS",
    /**
     * value: "ENVIRONMENT"
     * @const
     */
    "ENVIRONMENT": "ENVIRONMENT",
    /**
     * value: "REVISION"
     * @const
     */
    "REVISION": "REVISION",
    /**
     * value: "TEAM"
     * @const
     */
    "TEAM": "TEAM",
    /**
     * value: "DEPLOYMENT"
     * @const
     */
    "DEPLOYMENT": "DEPLOYMENT",
    /**
     * value: "GATEWAY"
     * @const
     */
    "GATEWAY": "GATEWAY"  };


  return exports;
}));


