/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeploymentScheduleBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DeploymentScheduleBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.DeploymentBean = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.DeploymentScheduleBean);
  }
}(this, function(ApiClient, DeploymentScheduleBean) {
  'use strict';




  /**
   * The DeploymentBean model module.
   * @module model/DeploymentBean
   * @version 2.0
   */

  /**
   * Constructs a new <code>DeploymentBean</code>.
   * @alias module:model/DeploymentBean
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>DeploymentBean</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploymentBean} obj Optional instance to populate.
   * @return {module:model/DeploymentBean} The populated <code>DeploymentBean</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiDescription')) {
        obj['apiDescription'] = ApiClient.convertToType(data['apiDescription'], 'String');
      }
      if (data.hasOwnProperty('apiId')) {
        obj['apiId'] = ApiClient.convertToType(data['apiId'], 'Number');
      }
      if (data.hasOwnProperty('apiName')) {
        obj['apiName'] = ApiClient.convertToType(data['apiName'], 'String');
      }
      if (data.hasOwnProperty('deployDate')) {
        obj['deployDate'] = ApiClient.convertToType(data['deployDate'], 'Date');
      }
      if (data.hasOwnProperty('deploymentSchedule')) {
        obj['deploymentSchedule'] = DeploymentScheduleBean.constructFromObject(data['deploymentSchedule']);
      }
      if (data.hasOwnProperty('environmentId')) {
        obj['environmentId'] = ApiClient.convertToType(data['environmentId'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('revisionId')) {
        obj['revisionId'] = ApiClient.convertToType(data['revisionId'], 'Number');
      }
      if (data.hasOwnProperty('revisionNumber')) {
        obj['revisionNumber'] = ApiClient.convertToType(data['revisionNumber'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} apiDescription
   */
  exports.prototype['apiDescription'] = undefined;
  /**
   * @member {Number} apiId
   */
  exports.prototype['apiId'] = undefined;
  /**
   * @member {String} apiName
   */
  exports.prototype['apiName'] = undefined;
  /**
   * @member {Date} deployDate
   */
  exports.prototype['deployDate'] = undefined;
  /**
   * @member {module:model/DeploymentScheduleBean} deploymentSchedule
   */
  exports.prototype['deploymentSchedule'] = undefined;
  /**
   * @member {Number} environmentId
   */
  exports.prototype['environmentId'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} revisionId
   */
  exports.prototype['revisionId'] = undefined;
  /**
   * @member {Number} revisionNumber
   */
  exports.prototype['revisionNumber'] = undefined;
  /**
   * @member {module:model/DeploymentBean.StatusEnum} status
   */
  exports.prototype['status'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "DEPLOYED"
     * @const
     */
    "DEPLOYED": "DEPLOYED",
    /**
     * value: "UNDEPLOYED"
     * @const
     */
    "UNDEPLOYED": "UNDEPLOYED"  };


  return exports;
}));


