/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InterceptorBean', 'model/OperationUrlBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InterceptorBean'), require('./OperationUrlBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.OperationBean = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.InterceptorBean, root.ApiManagerPortal.OperationUrlBean);
  }
}(this, function(ApiClient, InterceptorBean, OperationUrlBean) {
  'use strict';




  /**
   * The OperationBean model module.
   * @module model/OperationBean
   * @version 2.0
   */

  /**
   * Constructs a new <code>OperationBean</code>.
   * @alias module:model/OperationBean
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>OperationBean</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationBean} obj Optional instance to populate.
   * @return {module:model/OperationBean} The populated <code>OperationBean</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiBroken')) {
        obj['apiBroken'] = ApiClient.convertToType(data['apiBroken'], 'Boolean');
      }
      if (data.hasOwnProperty('async')) {
        obj['async'] = ApiClient.convertToType(data['async'], 'Boolean');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('destination')) {
        obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('interceptors')) {
        obj['interceptors'] = ApiClient.convertToType(data['interceptors'], [InterceptorBean]);
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('timeout')) {
        obj['timeout'] = ApiClient.convertToType(data['timeout'], 'String');
      }
      if (data.hasOwnProperty('urls')) {
        obj['urls'] = ApiClient.convertToType(data['urls'], [OperationUrlBean]);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} apiBroken
   */
  exports.prototype['apiBroken'] = undefined;
  /**
   * @member {Boolean} async
   */
  exports.prototype['async'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} destination
   */
  exports.prototype['destination'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/InterceptorBean>} interceptors
   */
  exports.prototype['interceptors'] = undefined;
  /**
   * @member {String} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * @member {String} timeout
   */
  exports.prototype['timeout'] = undefined;
  /**
   * @member {Array.<module:model/OperationUrlBean>} urls
   */
  exports.prototype['urls'] = undefined;



  return exports;
}));


