/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.OperationMetric = factory(root.ApiManagerPortal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OperationMetric model module.
   * @module model/OperationMetric
   * @version 2.0
   */

  /**
   * Constructs a new <code>OperationMetric</code>.
   * @alias module:model/OperationMetric
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>OperationMetric</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationMetric} obj Optional instance to populate.
   * @return {module:model/OperationMetric} The populated <code>OperationMetric</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('avgLatency')) {
        obj['avgLatency'] = ApiClient.convertToType(data['avgLatency'], 'Number');
      }
      if (data.hasOwnProperty('cacheCount')) {
        obj['cacheCount'] = ApiClient.convertToType(data['cacheCount'], 'Number');
      }
      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Number');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('hitsWithCache')) {
        obj['hitsWithCache'] = ApiClient.convertToType(data['hitsWithCache'], 'Number');
      }
      if (data.hasOwnProperty('hitsWithoutCache')) {
        obj['hitsWithoutCache'] = ApiClient.convertToType(data['hitsWithoutCache'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} avgLatency
   */
  exports.prototype['avgLatency'] = undefined;
  /**
   * @member {Number} cacheCount
   */
  exports.prototype['cacheCount'] = undefined;
  /**
   * @member {Number} count
   */
  exports.prototype['count'] = undefined;
  /**
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {Number} hitsWithCache
   */
  exports.prototype['hitsWithCache'] = undefined;
  /**
   * @member {Number} hitsWithoutCache
   */
  exports.prototype['hitsWithoutCache'] = undefined;



  return exports;
}));


