/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.OperationHealth = factory(root.ApiManagerPortal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OperationHealth model module.
   * @module model/OperationHealth
   * @version 2.0
   */

  /**
   * Constructs a new <code>OperationHealth</code>.
   * @alias module:model/OperationHealth
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>OperationHealth</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationHealth} obj Optional instance to populate.
   * @return {module:model/OperationHealth} The populated <code>OperationHealth</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('last24Hours')) {
        obj['last24Hours'] = ApiClient.convertToType(data['last24Hours'], 'Number');
      }
      if (data.hasOwnProperty('lastHour')) {
        obj['lastHour'] = ApiClient.convertToType(data['lastHour'], 'Number');
      }
      if (data.hasOwnProperty('lastMonth')) {
        obj['lastMonth'] = ApiClient.convertToType(data['lastMonth'], 'Number');
      }
      if (data.hasOwnProperty('lastWeek')) {
        obj['lastWeek'] = ApiClient.convertToType(data['lastWeek'], 'Number');
      }
      if (data.hasOwnProperty('operation')) {
        obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} last24Hours
   */
  exports.prototype['last24Hours'] = undefined;
  /**
   * @member {Number} lastHour
   */
  exports.prototype['lastHour'] = undefined;
  /**
   * @member {Number} lastMonth
   */
  exports.prototype['lastMonth'] = undefined;
  /**
   * @member {Number} lastWeek
   */
  exports.prototype['lastWeek'] = undefined;
  /**
   * @member {String} operation
   */
  exports.prototype['operation'] = undefined;



  return exports;
}));


