/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISimpleBean', 'model/InterceptorBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISimpleBean'), require('./InterceptorBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.PlanResponse = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.APISimpleBean, root.ApiManagerPortal.InterceptorBean);
  }
}(this, function(ApiClient, APISimpleBean, InterceptorBean) {
  'use strict';




  /**
   * The PlanResponse model module.
   * @module model/PlanResponse
   * @version 2.0
   */

  /**
   * Constructs a new <code>PlanResponse</code>.
   * Response create or update plan
   * @alias module:model/PlanResponse
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PlanResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PlanResponse} obj Optional instance to populate.
   * @return {module:model/PlanResponse} The populated <code>PlanResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('api')) {
        obj['api'] = APISimpleBean.constructFromObject(data['api']);
      }
      if (data.hasOwnProperty('defaultPlan')) {
        obj['defaultPlan'] = ApiClient.convertToType(data['defaultPlan'], 'Boolean');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('interceptors')) {
        obj['interceptors'] = ApiClient.convertToType(data['interceptors'], [InterceptorBean]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/APISimpleBean} api
   */
  exports.prototype['api'] = undefined;
  /**
   * @member {Boolean} defaultPlan
   */
  exports.prototype['defaultPlan'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/InterceptorBean>} interceptors
   */
  exports.prototype['interceptors'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


