/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/API', 'model/DeploymentBean', 'model/InterceptorBean', 'model/ResourceBean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./API'), require('./DeploymentBean'), require('./InterceptorBean'), require('./ResourceBean'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiManagerPortal) {
      root.ApiManagerPortal = {};
    }
    root.ApiManagerPortal.RevisionBean = factory(root.ApiManagerPortal.ApiClient, root.ApiManagerPortal.API, root.ApiManagerPortal.DeploymentBean, root.ApiManagerPortal.InterceptorBean, root.ApiManagerPortal.ResourceBean);
  }
}(this, function(ApiClient, API, DeploymentBean, InterceptorBean, ResourceBean) {
  'use strict';




  /**
   * The RevisionBean model module.
   * @module model/RevisionBean
   * @version 2.0
   */

  /**
   * Constructs a new <code>RevisionBean</code>.
   * @alias module:model/RevisionBean
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>RevisionBean</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevisionBean} obj Optional instance to populate.
   * @return {module:model/RevisionBean} The populated <code>RevisionBean</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('api')) {
        obj['api'] = API.constructFromObject(data['api']);
      }
      if (data.hasOwnProperty('apiBroken')) {
        obj['apiBroken'] = ApiClient.convertToType(data['apiBroken'], 'Boolean');
      }
      if (data.hasOwnProperty('creationDate')) {
        obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
      }
      if (data.hasOwnProperty('deployments')) {
        obj['deployments'] = ApiClient.convertToType(data['deployments'], [DeploymentBean]);
      }
      if (data.hasOwnProperty('destination')) {
        obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('interceptors')) {
        obj['interceptors'] = ApiClient.convertToType(data['interceptors'], [InterceptorBean]);
      }
      if (data.hasOwnProperty('lifeCycle')) {
        obj['lifeCycle'] = ApiClient.convertToType(data['lifeCycle'], 'String');
      }
      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], [ResourceBean]);
      }
      if (data.hasOwnProperty('revisionNumber')) {
        obj['revisionNumber'] = ApiClient.convertToType(data['revisionNumber'], 'Number');
      }
      if (data.hasOwnProperty('timeout')) {
        obj['timeout'] = ApiClient.convertToType(data['timeout'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/API} api
   */
  exports.prototype['api'] = undefined;
  /**
   * @member {Boolean} apiBroken
   */
  exports.prototype['apiBroken'] = undefined;
  /**
   * @member {Date} creationDate
   */
  exports.prototype['creationDate'] = undefined;
  /**
   * @member {Array.<module:model/DeploymentBean>} deployments
   */
  exports.prototype['deployments'] = undefined;
  /**
   * @member {String} destination
   */
  exports.prototype['destination'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/InterceptorBean>} interceptors
   */
  exports.prototype['interceptors'] = undefined;
  /**
   * @member {module:model/RevisionBean.LifeCycleEnum} lifeCycle
   */
  exports.prototype['lifeCycle'] = undefined;
  /**
   * @member {Array.<module:model/ResourceBean>} resources
   */
  exports.prototype['resources'] = undefined;
  /**
   * @member {Number} revisionNumber
   */
  exports.prototype['revisionNumber'] = undefined;
  /**
   * @member {String} timeout
   */
  exports.prototype['timeout'] = undefined;


  /**
   * Allowed values for the <code>lifeCycle</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LifeCycleEnum = {
    /**
     * value: "DRAFT"
     * @const
     */
    "DRAFT": "DRAFT",
    /**
     * value: "AVAILABLE"
     * @const
     */
    "AVAILABLE": "AVAILABLE",
    /**
     * value: "RETIRED"
     * @const
     */
    "RETIRED": "RETIRED"  };


  return exports;
}));


