/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.AccessToken();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccessToken', function() {
    it('should create an instance of AccessToken', function() {
      // uncomment below and update the code to test AccessToken
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be.a(ApiManagerPortal.AccessToken);
    });

    it('should have the property apis (base name: "apis")', function() {
      // uncomment below and update the code to test the property apis
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property app (base name: "app")', function() {
      // uncomment below and update the code to test the property app
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creationDate")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property expiredDate (base name: "expiredDate")', function() {
      // uncomment below and update the code to test the property expiredDate
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property expiresIn (base name: "expiresIn")', function() {
      // uncomment below and update the code to test the property expiresIn
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property extraInfo (base name: "extraInfo")', function() {
      // uncomment below and update the code to test the property extraInfo
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property planIds (base name: "planIds")', function() {
      // uncomment below and update the code to test the property planIds
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property refreshToken (base name: "refreshToken")', function() {
      // uncomment below and update the code to test the property refreshToken
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ApiManagerPortal.AccessToken();
      //expect(instance).to.be();
    });

  });

}));
