/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.APP();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APP', function() {
    it('should create an instance of APP', function() {
      // uncomment below and update the code to test APP
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be.a(ApiManagerPortal.APP);
    });

    it('should have the property accessTokens (base name: "accessTokens")', function() {
      // uncomment below and update the code to test the property accessTokens
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property apis (base name: "apis")', function() {
      // uncomment below and update the code to test the property apis
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "clientId")', function() {
      // uncomment below and update the code to test the property clientId
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creationDate")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property developer (base name: "developer")', function() {
      // uncomment below and update the code to test the property developer
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property extraInfo (base name: "extraInfo")', function() {
      // uncomment below and update the code to test the property extraInfo
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property secret (base name: "secret")', function() {
      // uncomment below and update the code to test the property secret
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property showAppGallery (base name: "showAppGallery")', function() {
      // uncomment below and update the code to test the property showAppGallery
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ApiManagerPortal.APP();
      //expect(instance).to.be();
    });

  });

}));
