/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.LatencyMetric();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LatencyMetric', function() {
    it('should create an instance of LatencyMetric', function() {
      // uncomment below and update the code to test LatencyMetric
      //var instane = new ApiManagerPortal.LatencyMetric();
      //expect(instance).to.be.a(ApiManagerPortal.LatencyMetric);
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instane = new ApiManagerPortal.LatencyMetric();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new ApiManagerPortal.LatencyMetric();
      //expect(instance).to.be();
    });

    it('should have the property latencyMillis (base name: "latencyMillis")', function() {
      // uncomment below and update the code to test the property latencyMillis
      //var instane = new ApiManagerPortal.LatencyMetric();
      //expect(instance).to.be();
    });

    it('should have the property totalLatency (base name: "totalLatency")', function() {
      // uncomment below and update the code to test the property totalLatency
      //var instane = new ApiManagerPortal.LatencyMetric();
      //expect(instance).to.be();
    });

  });

}));
