/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.OperationHealth();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OperationHealth', function() {
    it('should create an instance of OperationHealth', function() {
      // uncomment below and update the code to test OperationHealth
      //var instane = new ApiManagerPortal.OperationHealth();
      //expect(instance).to.be.a(ApiManagerPortal.OperationHealth);
    });

    it('should have the property last24Hours (base name: "last24Hours")', function() {
      // uncomment below and update the code to test the property last24Hours
      //var instane = new ApiManagerPortal.OperationHealth();
      //expect(instance).to.be();
    });

    it('should have the property lastHour (base name: "lastHour")', function() {
      // uncomment below and update the code to test the property lastHour
      //var instane = new ApiManagerPortal.OperationHealth();
      //expect(instance).to.be();
    });

    it('should have the property lastMonth (base name: "lastMonth")', function() {
      // uncomment below and update the code to test the property lastMonth
      //var instane = new ApiManagerPortal.OperationHealth();
      //expect(instance).to.be();
    });

    it('should have the property lastWeek (base name: "lastWeek")', function() {
      // uncomment below and update the code to test the property lastWeek
      //var instane = new ApiManagerPortal.OperationHealth();
      //expect(instance).to.be();
    });

    it('should have the property operation (base name: "operation")', function() {
      // uncomment below and update the code to test the property operation
      //var instane = new ApiManagerPortal.OperationHealth();
      //expect(instance).to.be();
    });

  });

}));
