/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.UserBean();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserBean', function() {
    it('should create an instance of UserBean', function() {
      // uncomment below and update the code to test UserBean
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be.a(ApiManagerPortal.UserBean);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property hasAllPermissions (base name: "hasAllPermissions")', function() {
      // uncomment below and update the code to test the property hasAllPermissions
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property login (base name: "login")', function() {
      // uncomment below and update the code to test the property login
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property passwordConfirm (base name: "passwordConfirm")', function() {
      // uncomment below and update the code to test the property passwordConfirm
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property roles (base name: "roles")', function() {
      // uncomment below and update the code to test the property roles
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property teamUserId (base name: "teamUserId")', function() {
      // uncomment below and update the code to test the property teamUserId
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property teams (base name: "teams")', function() {
      // uncomment below and update the code to test the property teams
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

    it('should have the property userType (base name: "userType")', function() {
      // uncomment below and update the code to test the property userType
      //var instane = new ApiManagerPortal.UserBean();
      //expect(instance).to.be();
    });

  });

}));
