/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.AccessTokensApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccessTokensApi', function() {
    describe('countUsingGET10', function() {
      it('should call countUsingGET10 successfully', function(done) {
        //uncomment below and update the code to test countUsingGET10
        //instance.countUsingGET10(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeAuthTokenUsingDELETE1', function() {
      it('should call removeAuthTokenUsingDELETE1 successfully', function(done) {
        //uncomment below and update the code to test removeAuthTokenUsingDELETE1
        //instance.removeAuthTokenUsingDELETE1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveAuthTokenChangeLogUsingGET1', function() {
      it('should call retrieveAuthTokenChangeLogUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test retrieveAuthTokenChangeLogUsingGET1
        //instance.retrieveAuthTokenChangeLogUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retriveAuthTokenByCodeUsingGET1', function() {
      it('should call retriveAuthTokenByCodeUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test retriveAuthTokenByCodeUsingGET1
        //instance.retriveAuthTokenByCodeUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retriveAuthTokenUsingGET1', function() {
      it('should call retriveAuthTokenUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test retriveAuthTokenUsingGET1
        //instance.retriveAuthTokenUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('saveAuthTokenUsingPOST1', function() {
      it('should call saveAuthTokenUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test saveAuthTokenUsingPOST1
        //instance.saveAuthTokenUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAuthTokenUsingPUT1', function() {
      it('should call updateAuthTokenUsingPUT1 successfully', function(done) {
        //uncomment below and update the code to test updateAuthTokenUsingPUT1
        //instance.updateAuthTokenUsingPUT1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validatePartialAccessTokenUsingPOST1', function() {
      it('should call validatePartialAccessTokenUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test validatePartialAccessTokenUsingPOST1
        //instance.validatePartialAccessTokenUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
