/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.AppsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AppsApi', function() {
    describe('countUsingGET11', function() {
      it('should call countUsingGET11 successfully', function(done) {
        //uncomment below and update the code to test countUsingGET11
        //instance.countUsingGET11(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAppTokenUsingDELETE1', function() {
      it('should call deleteAppTokenUsingDELETE1 successfully', function(done) {
        //uncomment below and update the code to test deleteAppTokenUsingDELETE1
        //instance.deleteAppTokenUsingDELETE1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppTokenByAppGalleryUsingGET1', function() {
      it('should call getAppTokenByAppGalleryUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getAppTokenByAppGalleryUsingGET1
        //instance.getAppTokenByAppGalleryUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppTokenByFilterUsingGET1', function() {
      it('should call getAppTokenByFilterUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getAppTokenByFilterUsingGET1
        //instance.getAppTokenByFilterUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppTokenByIdUsingGET1', function() {
      it('should call getAppTokenByIdUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getAppTokenByIdUsingGET1
        //instance.getAppTokenByIdUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppTokenChangeLogUsingGET1', function() {
      it('should call getAppTokenChangeLogUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getAppTokenChangeLogUsingGET1
        //instance.getAppTokenChangeLogUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAppTokenUsingPOST1', function() {
      it('should call postAppTokenUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test postAppTokenUsingPOST1
        //instance.postAppTokenUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putAppTokenUsingPUT1', function() {
      it('should call putAppTokenUsingPUT1 successfully', function(done) {
        //uncomment below and update the code to test putAppTokenUsingPUT1
        //instance.putAppTokenUsingPUT1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validatePartialAppUsingPOST1', function() {
      it('should call validatePartialAppUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test validatePartialAppUsingPOST1
        //instance.validatePartialAppUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
