/**
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiManagerPortal);
  }
}(this, function(expect, ApiManagerPortal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiManagerPortal.PlansApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlansApi', function() {
    describe('clonePlanUsingPOST1', function() {
      it('should call clonePlanUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test clonePlanUsingPOST1
        //instance.clonePlanUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countUsingGET13', function() {
      it('should call countUsingGET13 successfully', function(done) {
        //uncomment below and update the code to test countUsingGET13
        //instance.countUsingGET13(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePlanUsingDELETE1', function() {
      it('should call deletePlanUsingDELETE1 successfully', function(done) {
        //uncomment below and update the code to test deletePlanUsingDELETE1
        //instance.deletePlanUsingDELETE1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlanChangeLogUsingGET3', function() {
      it('should call getPlanChangeLogUsingGET3 successfully', function(done) {
        //uncomment below and update the code to test getPlanChangeLogUsingGET3
        //instance.getPlanChangeLogUsingGET3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlanDefaultByApiUsingGET1', function() {
      it('should call getPlanDefaultByApiUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test getPlanDefaultByApiUsingGET1
        //instance.getPlanDefaultByApiUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlanUsingGET2', function() {
      it('should call getPlanUsingGET2 successfully', function(done) {
        //uncomment below and update the code to test getPlanUsingGET2
        //instance.getPlanUsingGET2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlanUsingGET3', function() {
      it('should call getPlanUsingGET3 successfully', function(done) {
        //uncomment below and update the code to test getPlanUsingGET3
        //instance.getPlanUsingGET3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postPlanUsingPOST1', function() {
      it('should call postPlanUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test postPlanUsingPOST1
        //instance.postPlanUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putPlanUsingPUT1', function() {
      it('should call putPlanUsingPUT1 successfully', function(done) {
        //uncomment below and update the code to test putPlanUsingPUT1
        //instance.putPlanUsingPUT1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validatePartialPlanUsingPOST1', function() {
      it('should call validatePartialPlanUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test validatePartialPlanUsingPOST1
        //instance.validatePartialPlanUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
